# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdaef0cbd2cc6fad5d42a4ba18918eda500863e33f0a9cca46cc1230466d4ee43adc5f828271631f457a9ca438f7e43cfae7c3ed0dbd48475e77e3028d36b870

test:
  secret_key_base: a21064e17f480a72da9398b8bdd70d7670641f1073c9d2e54ce6d25f255afe458d8980c5c2633ce8bf8f10039d6f72a9ac155150c2343b44ec1b51dc7f7f855d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
